default_agent: customer_support_agent
agents:
  customer_support_agent:
    name: customer_support_agent
    language: python
    node_version: '20'
    entrypoint: C:/Users/clene/Downloads/AWS - AI Support Agent/cd14763-project-starter/starter/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\clene\Downloads\AWS - AI Support Agent\cd14763-project-starter\starter
    aws:
      execution_role: arn:aws:iam::093325579981:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-aa96c3a063
      execution_role_auto_create: false
      account: 093325579981
      region: us-east-1
      ecr_repository: 093325579981.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-customer_support_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: customer_support_agent-mg3iJ3AQ0b
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:093325579981:runtime/customer_support_agent-mg3iJ3AQ0b
      agent_session_id: d420e0ad-810e-4a8b-9ea9-ebd30a30e640
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: CustomerSupportMemory-7gBufM9tWh
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:093325579981:memory/customer_support_agent_mem-9iKRsK20Dp
      memory_name: CustomerSupportMemory
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
